### ISSUE TITLE
bass.pas is skipped

### ISSUE THREAD

**Issue by Al-Muhandis** [r1me/TPocketSphinx#2]
Hi @r1me !
One unit (`bass.pas`) is skipped in the repository in the [bass example](https://github.com/r1me/TPocketSphinx/tree/master/examples/bass)

Thanks for lib

**Comment by r1me** [comment]
That example will be removed from next version of TPocketSphinx anyway, and replaced with [PortAudio](http://www.portaudio.com/). Mostly due to BASS license and the fact that it isn't free for commercial usage, while I want to keep TPocketSphinx as friendly as possible for both commercial and non-commercial projects. If you still want to test BASS example, you can get bass.pas from http://www.un4seen.com/download.php?bass24

**Comment by Al-Muhandis** [comment]
There is a trunk version? I don't need that example. Just when I looked at the demo code, I saw that the sample in bass folder is not run to due to the lack of a file.
Overall, it is clear
